version: '2'
services:
 kafkaserver:
      image: spotify/kafka
      mem_limit: 1073741824
      ports:
        - 2181:2181
        - 9092:9092
#      environment:
#        - ADVERTISED_HOST=localhost
#        - ADVERTISED_PORT=9092
 redis:
    image: redis:alpine
    ports:
      - 6379:6379
 database:
      image: postgres:9.5
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=dev_db
 eureka-service:
   image: akaczmarek/eureka-service:${BUILD_NAME_SCT}
   mem_limit: 3000m
   ports:
      - "8761:8761"
   environment:
      TZ: Europe/Berlin
 config-service:
   image: akaczmarek/config-service:${BUILD_NAME_SCT}
   mem_limit: 2500m
   ports:
     - "8888:8888"
   links:
     - "eureka-service:eureka-service"
   environment:
     EUREKASERVER_URI: "http://eureka-service:8761/eureka/"
     EUREKASERVER_PORT: "8761"
     ENCRYPT_KEY: "SPRING_CLOUD_DEV"
     TZ: Europe/Berlin
 zuul-service:
    image: akaczmarek/zuul-service:${BUILD_NAME_SCT}
    mem_limit: 3000m
    ports:
      - "5555:5555"
    links:
      - "config-service:config-service"
      - "eureka-service:eureka-service"
    environment:
      PROFILE: "dev"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://config-service:8888"
      EUREKASERVER_URI: "http://eureka-service:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      CONFIGSERVER_PORT:        "8888"
      TZ: Europe/Berlin


 authentication-service:
    image: akaczmarek/authentication-service:${BUILD_NAME_SCT}
    mem_limit: 2500m
    ports:
      - "8901:8901"
    links:
      - "config-service:config-service"
      - "eureka-service:eureka-service"
      - "zuul-service:zuul-service"
    environment:
      PROFILE: "dev"
      SERVER_PORT: "8901"
      DATABASE_PORT:     5432
      CONFIGSERVER_PORT: 8888
      EUREKASERVER_PORT: 8761
      CONFIGSERVER_URI: "http://config-service:8888"
      EUREKASERVER_URI: "http://eureka-service:8761/eureka/"
      ENCRYPT_KEY:       "SPRING_CLOUD_DEV"
      TZ: Europe/Berlin

 device-registration-service:
    image: akaczmarek/device-registration-service:${BUILD_NAME}
    mem_limit: 2500m
    ports:
      - "8083:8083"
    links:
      - "config-service:config-service"
      - "eureka-service:eureka-service"
      - "zuul-service:zuul-service"
      - "authentication-service"
    environment:
      PROFILE: "dev"
      SERVER_PORT: "8083"
      CONFIGSERVER_URI: "http://config-service:8888"
      EUREKASERVER_URI: "http://eureka-service:8761/eureka/"
      AUTHSERVER_URI:  "http://authentication-service:8901/auth/user"
      CONFIGSERVER_PORT:   8888
      DATABASE_PORT:       5432
      EUREKASERVER_PORT:   8761
      ZULLSERVER_PORT:     5555
      AUTHSERVER_PORT:     8091
      ENCRYPT_KEY:     "SPRING_CLOUD_DEV"
      AWS_KEY_ID : ${AWS_KEY_ID}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      TZ: Europe/Berlin

 device-controller-service:
    image: akaczmarek/device-controller-service:${BUILD_NAME}
    mem_limit: 2500m
    ports:
      - "8087:8087"
    links:
      - "config-service:config-service"
      - "eureka-service:eureka-service"
      - "zuul-service:zuul-service"
      - "authentication-service"
      - "device-registration-service:device-registration-service"
    environment:
      PROFILE: "dev"
      SERVER_PORT: "8087"
      CONFIGSERVER_URI: "http://config-service:8888"
      EUREKASERVER_URI: "http://eureka-service:8761/eureka/"
      AUTHSERVER_URI:  "http://authentication-service:8901/auth/user"
      CONFIGSERVER_PORT:   "8888"
      DATABASE_PORT:     "5432"
      EUREKASERVER_PORT:   "8761"
      ZULLSERVER_PORT: "5555"
      AUTHSERVER_PORT: "8091"
      DEVICE_REG_PORT: "8083"
      ENCRYPT_KEY:     "SPRING_CLOUD_DEV"
      AWS_KEY_ID : ${AWS_KEY_ID}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      TZ: Europe/Berlin

 device-data-service:
    image: akaczmarek/device-data-service:${BUILD_NAME}
    mem_limit: 2500m
    ports:
      - "8086:8086"
    links:
      - "config-service:config-service"
      - "eureka-service:eureka-service"
      - "zuul-service:zuul-service"
      - "authentication-service"
    environment:
      PROFILE: "dev"
      SERVER_PORT: "8086"
      CONFIGSERVER_URI: "http://config-service:8888"
      EUREKASERVER_URI: "http://eureka-service:8761/eureka/"
      AUTHSERVER_URI:  "http://authentication-service:8901/auth/user"
      CONFIGSERVER_PORT:   "8888"
      DATABASE_PORT:     "5432"
      EUREKASERVER_PORT:   "8761"
      ZULLSERVER_PORT: "5555"
      AUTHSERVER_PORT: "8091"
      ENCRYPT_KEY:       "SPRING_CLOUD_DEV"
      AWS_KEY_ID : ${AWS_KEY_ID}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      TZ: Europe/Berlin

# device-state-service:
#    image: akaczmarek/device-state-service:${BUILD_NAME}
#    mem_limit: 2500m
#    ports:
#      - "8084:8084"
#    links:
#      - "config-service:config-service"
#      - "eureka-service:eureka-service"
#      - "zuul-service:zuul-service"
#      - "authentication-service"
#    environment:
#      PROFILE: "aws-dev"
#      SERVER_PORT: "8084"
#      CONFIGSERVER_URI: "http://config-service:8888"
#      EUREKASERVER_URI: "http://eureka-service:8761/eureka/"
#      AUTHSERVER_URI:  "http://authentication-service:8901/auth/user"
#      CONFIGSERVER_PORT:   "8888"
#      DATABASE_PORT:     "5432"
#      EUREKASERVER_PORT:   "8761"
#      ZULLSERVER_PORT: "5555"
#      AUTHSERVER_PORT: "8091"
#      ENCRYPT_KEY:       "SPRING_CLOUD_DEV"

