version: '2'
services:

#  database:
#      image: postgres:9.5
#      ports:
#        - "5432:5432"
#      environment:
#        - POSTGRES_USER=postgres
#        - POSTGRES_PASSWORD=p0stgr@s
#        - POSTGRES_DB=devices_db


  device-registration-service:
      image: homesamples/device-registration-service:homesamples
      ports:
        - "8083:8083"
      environment:
        PROFILE: "aws-dev"
        SERVER_PORT: "8083"
        CONFIGSERVER_URI: "http://config-service:8888"
        EUREKASERVER_URI: "http://eureka-service:8761/eureka/"
        AUTHSERVER_URI:  "http://authentication-service:8901/auth/user"
        CONFIGSERVER_PORT:   "8888"
        DATABASE_PORT:     "5432"
        EUREKASERVER_PORT:   "8761"
        ZULLSERVER_PORT: "5555"
        AUTHSERVER_PORT: "8091"
        ENCRYPT_KEY:       "SPRING_CLOUD_DEV"

  device-data-service:
        image: homesamples/device-data-service:homesamples
        ports:
          - "8086:8086"
        environment:
          PROFILE: "aws-dev"
          SERVER_PORT: "8086"
          CONFIGSERVER_URI: "http://config-service:8888"
          EUREKASERVER_URI: "http://eureka-service:8761/eureka/"
          AUTHSERVER_URI:  "http://authentication-service:8901/auth/user"
          CONFIGSERVER_PORT:   "8888"
          DATABASE_PORT:     "5432"
          EUREKASERVER_PORT:   "8761"
          ZULLSERVER_PORT: "5555"
          AUTHSERVER_PORT: "8091"
          ENCRYPT_KEY:       "SPRING_CLOUD_DEV"

  device-state-service:
        image: homesamples/device-state-service:homesamples
        ports:
          - "8084:8084"
        environment:
          PROFILE: "aws-dev"
          SERVER_PORT: "8084"
          CONFIGSERVER_URI: "http://config-service:8888"
          EUREKASERVER_URI: "http://eureka-service:8761/eureka/"
          AUTHSERVER_URI:  "http://authentication-service:8901/auth/user"
          CONFIGSERVER_PORT:   "8888"
          DATABASE_PORT:     "5432"
          EUREKASERVER_PORT:   "8761"
          ZULLSERVER_PORT: "5555"
          AUTHSERVER_PORT: "8091"
          ENCRYPT_KEY:       "SPRING_CLOUD_DEV"