DROP TABLE IF EXISTS RFID_DATA;
DROP TABLE IF EXISTS DHT22_DATA;

CREATE TABLE RFID_DATA(
  ID          BIGSERIAL PRIMARY KEY NOT NULL,
  UID_TAG     VARCHAR(100) NOT NULL,
  DEVICE_ID   VARCHAR(100) NOT NULL,
  CREATION_DATE TIMESTAMP  NOT NULL
  );

CREATE TABLE DHT22_DATA(
  DTH22_DATA_ID          BIGSERIAL PRIMARY KEY NOT NULL,
  TEMP     NUMERIC NOT NULL,
  HUMIDITY NUMERIC NOT NULL,
  DEVICE_ID   VARCHAR(100) NOT NULL,
  CREATION_DATE TIMESTAMP  NOT NULL
);