DROP TABLE IF EXISTS RFID_DATA;

CREATE TABLE RFID_DATA(
  ID          BIGINT PRIMARY KEY NOT NULL,
  UID_TAG     VARCHAR(100) NOT NULL,
  DEVICE_ID   VARCHAR(100) NOT NULL,
  CREATION_DATE TIMESTAMP  NOT NULL
  );
